version: '3.8'
services:
  admin_api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_db:
    container_name: django_admin_db
    image: "arm64v8/mysql:8.0.30"
    restart: always
    environment:
      MYSQL_DATABASE: django_admin
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306