# Generated by Django 4.2 on 2023-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_role_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission',
            new_name='permissions',
        ),
    ]
